storeproject/storeapp/urls.py
from django.urls import path
from . import views

app_name = "storeapp"

urlpatterns = [
    path('home/',views.demo,name='demo'),
    #path('login', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('home/order/',views.order, name='order'),
    path('logout/', views.logout, name='logout'),
]

storeproject/storeproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from storeproject import settings

urlpatterns=[
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
]
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

storeproject/storeapp/models.py
from django.db import models
from django.urls import reverse
class Register(models.Model):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50,blank=False)
    def __str__(self):
        return self.username
class Dept(models.Model):
    dept = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return '{}'.format(self.dept)
class Course(models.Model):
    department = models.ForeignKey(Dept, on_delete=models.CASCADE)
    course = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.course)

storeproject/storeapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from storeapp.models import Register, Dept, Course

def demo(request):
    obj = Dept.objects.all()
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['psw']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('storeapp:order')
        else:
            messages.warning(request, "Username or Password is not valid    ")
    return render(request,'home.html',{'key1' : obj})
'''
def login(request):
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['psw']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('storeapp:order')
        else:
            messages.warning(request, "Invalid user")

    return render(request, 'login.html')
'''
def register(request):
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['psw']
        password2 = request.POST['psw2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exists")
                #return redirect('register')
            else :
                user = User.objects.create_user(username=username,password=password)
                user.save()
                return redirect('storeapp:demo')
        else :
            messages.info(request,"Password not matching")
            #return redirect('register')

    return render(request,'register.html')
def order(request):
    Deptobj = Dept.objects.all()
    Courseobj = Course.objects.all()
    if request.method == 'POST':
        messages.info(request, "Data sent successfully")
        return redirect('storeapp:order')

    return render(request, 'order.html', {'Deptobj': Deptobj, 'Courseobj':Courseobj})
def logout(request):
    auth.logout(request)
    return redirect('storeapp:demo')

storeproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>School Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
        (function () {
        	window.onpageshow = function(event) {
        		if (event.persisted) {
        			window.location.reload();
        		}
        	};
        })();
        </script>
    {% block myscript %}
    {% endblock %}
</head>
<body>
<div class="container">
{% block body %}
{% endblock %}
</div>
</body>
</html>

storeproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block myscript %}

{% endblock %}
{% block body %}

<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
    <ul class="nav navbar-nav mr-auto">

        {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'storeapp:logout' %}"> Logout({{user.username}}) </a> </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'storeapp:order' %}"> New Order </a> </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href=""> Login </a> </li>
        {% endif %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'storeapp:register' %}">Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" >
          Department
        </a>
        <ul class="nav-item dropdown-content bg-success" style="list-style-type: none; " >
          {% for i in key1 %}
          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/{{ i.dept }}">{{ i.dept }}</a></li>
          {% endfor %}
        </ul>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
    {% if user.is_authenticated %}
    <h2 class="welcome-title">
      Hello {{user.username}}, Welcome to School Store
    </h2>
    <img src="{% static 'images/img.png' %}" width="100%">
    {% else %}
    {% include 'login.html'  %}
    {% endif %}
</div>
{% endblock %}

storeproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div class="d-flex p-2 justify-content-center align-items-center">
<form method="post" class="">
{% csrf_token %}
  <div class="container">
    <input type="text" placeholder="Enter Username" name="name" required>
    <input type="password" placeholder="Enter Password" name="psw" required>
    <button type="submit">Login</button>
  </div>
  <div class="container">
    <span class="psw"><a href="{% url 'storeapp:register' %}">New User </a></span>
  </div>
</form>
  {% for i in  messages %}
  <h3 class="message" style=""> {{ i }} </h3>
  {% endfor %}
</div>

{% endblock %}

storeproject/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% include
{% block myscript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
$(document).ready(function()
{
     var $dept = $("#select1"),
         $course = $("#select2"),
         $options = $course.find('option');
     $dept.on('change',function()
     {
        $course.html($options.filter('[value="'+ this.value  +'"]'));
     }).trigger('change');
});

</script>

{% endblock %}

{% block body %}
<div class="container">
<form method="post">
  {% csrf_token %}
  <div class="container form-contents">
    <h1>Details </h1>
    <hr>
    <input type="text" placeholder="Full Name" name="name" id="name" required>
    <input type="number" placeholder="Age" name="psw" id="psw" min="17" max="30" required>
    <input type="radio" name="gender" id="male" required> Male
    <input type="radio" name="gender" id="female" required> <label for="female">Female</label>
    <input type="tel" placeholder="Mobile Number" name="mobile" id="mobile" pattern="[0-9]{10}" required>
    <input type="email" placeholder="email" name="name" id="email" required>
    <input type="text" placeholder="Address" name="address" id="address" maxlength="100" minlength="5" required>

    <select id="select1">
      <option value="0" selected="selected">Select Department</option>
       {% for i in Deptobj %}
          <option value="{{ i.id }}">{{i.dept}}</option>
        {% endfor %}
    </select>
    <select  id="select2">
      <option value="0" selected >Choose course</option>
      {% for i in Courseobj %}
          <option value="{{ i.department_id }}">{{i.course}}</option>
        {% endfor %}
    </select>

    <select name="dept" id="purpose">
      <option value="" selected="selected">Enquiry</option>
      <option value="" >Place Order</option>
      <option value="" >Return</option>
    </select>
    <input type="checkbox" id="material1" name="material1" value="Notebook"> Notebook
    <input type="checkbox" id="material2" name="material2" value="Pen"> Pen
    <input type="checkbox" id="material3" name="material3" value="Exam Papers"> Exam Papers

    <hr>
    <div style=" text-align: center;" >
    <button type="submit" class="orderbtn1">SUBMIT</button>
    <!--- <a href="{% url 'storeapp:logout' %}" class="orderbtn2"> LOGOUT </a> ---->
      </div>
  </div>
</form>
  {% for i in  messages %}
  <h3 class="message" style=""> {{ i }} </h3>
  {% endfor %}
</div>
{% endblock %}

storeproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container">
<form method="post">
  {% csrf_token %}
  <div class="container">
    <h1>Student Registration </h1>
    <hr>

    <input type="text" placeholder="Enter username" name="name" id="email" required>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required>
    <input type="password" placeholder="Confirm Password" name="psw2" id="psw-repeat" required>
    <hr>

    <button type="submit" class="registerbtn" onclick="checkfun()">SUBMIT</button>
  </div>
</form>
  {% for i in  messages %}
  <h3 class="message" style=""> {{ i }} </h3>
  {% endfor %}
</div>
{% endblock %}